import type { Theme } from '@mui/material';

export const styles = {
  root: () => (theme: Theme) => ({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
    marginBottom: theme.spacing(1.5),
    width: '100%',
  }),
  item: () => (theme: Theme) => ({
    width: '100%',
    borderRadius: theme.spacing(1),
    backgroundColor: 'rgba(5, 8, 30, 0.78)',
    color: theme.palette.common.white,
    backdropFilter: 'blur(8px)',
    boxShadow: '0 0 18px rgba(0, 0, 0, 0.45)',
    overflow: 'hidden',
  }),
  sectionHeader: () => (theme: Theme) => ({
    width: '100%',
    textAlign: 'left' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: 'none',
    background: 'transparent',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    padding: theme.spacing(1.25, 1.5),
  }),
  sectionContent: () => (theme: Theme) => ({
    padding: theme.spacing(0, 1.5, 1.5, 1.5),
  }),
  birthTitle: () => (theme: Theme) => ({
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0.5,
    marginBottom: theme.spacing(0.25),
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  birthMeta: () => (theme: Theme) => ({
    fontSize: 11,
    opacity: 0.85,
    lineHeight: 1.4,
  }),
  bigThreeLine: () => (theme: Theme) => ({
    fontSize: 11,
    lineHeight: 1.4,
    opacity: 0.9,
  }),
  bigThreeButton: () => (theme: Theme) => ({
    marginTop: theme.spacing(0.5),
    padding: theme.spacing(0.5, 1),
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'none',
    borderRadius: theme.spacing(0.5),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: theme.palette.common.white,
    border: '1px solid rgba(255, 255, 255, 0.2)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
  }),
  hintTitle: () => (theme: Theme) => ({
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0.5,
    marginBottom: theme.spacing(0.25),
  }),
  hintLine: () => (theme: Theme) => ({
    fontSize: 11,
    lineHeight: 1.4,
    display: 'block',
    width: '100%',
  }),
  icon: (isOpen: boolean) => ({
    display: 'inline-block',
    transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)',
    transition: 'transform 0.2s ease',
  }),
  expandButton: () => (theme: Theme) => ({
    marginTop: theme.spacing(0.5),
    padding: theme.spacing(0.5, 1),
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'none',
    borderRadius: theme.spacing(0.5),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: theme.palette.common.white,
    border: '1px solid rgba(255, 255, 255, 0.2)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
  }),
};
