import type { Theme } from '@mui/material';

export const styles = {
  overlay: () => (theme: Theme) => ({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100vw',
    height: '100vh',
    zIndex: 99999, // Very high z-index to appear above everything including navigation header
    backgroundColor: 'rgba(5, 8, 30, 0.95)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  }),
  closeButton: () => (theme: Theme) => ({
    position: 'absolute',
    top: theme.spacing(3),
    right: theme.spacing(2),
    zIndex: 100000,
    color: theme.palette.common.white,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
  }),
  content: () => (theme: Theme) => ({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    padding: theme.spacing(2),
    paddingTop: theme.spacing(8),
  }),
  interactionsAccordion: () => (theme: Theme) => ({
    width: '100%',
    marginBottom: theme.spacing(2),
    borderRadius: theme.spacing(1),
    backgroundColor: 'rgba(5, 8, 30, 0.78)',
    color: theme.palette.common.white,
    backdropFilter: 'blur(8px)',
    boxShadow: '0 0 18px rgba(0, 0, 0, 0.45)',
    overflow: 'hidden',
  }),
  accordionHeader: () => (theme: Theme) => ({
    width: '100%',
    textAlign: 'left' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: 'none',
    background: 'transparent',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.6,
    cursor: 'pointer',
    padding: theme.spacing(1.25, 1.5),
  }),
  accordionContent: () => (theme: Theme) => ({
    padding: theme.spacing(0, 1.5, 1.5, 1.5),
  }),
  hintTitle: () => (theme: Theme) => ({
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0.5,
    lineHeight: 1.6,
    marginBottom: theme.spacing(0.25),
  }),
  hintLine: (color?: string) => (theme: Theme) => ({
    fontSize: 13,
    lineHeight: 1.7,
    display: 'block',
    width: '100%',
    position: 'relative',
    paddingLeft: theme.spacing(2),
    '&::before': {
      content: '"✦"',
      position: 'absolute',
      left: 0,
      color: color || 'rgba(255, 255, 255, 0.7)',
      fontSize: '0.85em',
    },
  }),
  icon: (isOpen: boolean) => ({
    display: 'inline-block',
    transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)',
    transition: 'transform 0.2s ease',
  }),
  chartContainer: () => (theme: Theme) => ({
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
  }),
};
